# Site settings
title: HILITE Developer Documentation
email: jeff@betacamp.us
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://developer.hilite.media" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
api_host:  https://api.hilite.media

collections:
  specs:
    output: true
  endpoints:
    output: true

# Build settings
markdown: kramdown
highlighter: rouge
